spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: leandroj
  jpa:
    database: postgresql
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLInnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        '[globally_quoted_identifiers]': true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        '[format_sql]': true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  mvc:
    async:
      request-timeout: 3600000
server:
  port: 8081
  error:
    path: /user/error
    whitelabel:
      enabled: false
